databaseConfig:
  dbUsername: username
  dbPassword: password
  dbHostname: hostname
  dbPort: 3306
  dbDriver: com.mysql.cj.jdbc.Driver
  dbName: name
  dbSettings: ?autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST

serviceConfig:
  scheme: http://
  hostName: localhost
  port: 2942
  path: /api/test

loggerConfig:
  outputDir: ./logs/
  outputFile: test.log

